---
- block:
  - name: install percona package deb
    apt:
      deb: "https://repo.percona.com/apt/percona-release_latest.buster_all.deb"
  - name: enable percona repo
    command: "percona-release setup -y ps80"
  - name: install percona server
    apt: "pkg=percona-server-server state=latest update_cache=yes"
  tags:
    - percona
