---
- block:
  - name: install percona package deb
    apt:
      deb: "https://repo.percona.com/apt/percona-release_0.1-6.stretch_all.deb"
  - name: install percona server
    apt: "pkg=percona-server-server-5.7 state=latest update_cache=yes"
  tags:
    - percona
